param(
    [string]$Version = "0.1.0",
    [string]$Channel = "dev",
    [string]$BaseUrl = "http://127.0.0.1:8787",
    [string]$FirmwarePath = "idf\build\ouo_s31_bringup.bin",
    [string]$OutputDir = "server\ota"
)

$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$firmware = Join-Path $root $FirmwarePath
if (-not (Test-Path $firmware)) {
    throw "Firmware binary not found: $firmware. Run .\scripts\build-idf.ps1 first."
}

$otaDir = Join-Path $root $OutputDir
New-Item -ItemType Directory -Force $otaDir | Out-Null

$targetName = "ouo_s31_bringup.bin"
$target = Join-Path $otaDir $targetName
Copy-Item -Force $firmware $target

$hash = (Get-FileHash -Algorithm SHA256 $target).Hash.ToLowerInvariant()
$size = (Get-Item $target).Length
$firmwareUrl = "$($BaseUrl.TrimEnd('/'))/ota/$targetName"

$manifest = [ordered]@{
    version = $Version
    channel = $Channel
    firmware_url = $firmwareUrl
    sha256 = $hash
    size = $size
    notes = @(
        "Generated by scripts/publish-ota.ps1.",
        "Build idf/build/ouo_s31_bringup.bin before publishing."
    )
}

$manifestPath = Join-Path $otaDir "manifest.json"
$manifest | ConvertTo-Json -Depth 4 | Set-Content -Encoding utf8 $manifestPath

Write-Host "ota_manifest=$manifestPath"
Write-Host "firmware=$target"
Write-Host "version=$Version channel=$Channel size=$size sha256=$hash"
Write-Host "firmware_url=$firmwareUrl"
